services:
  bridge:
    build: .
    environment:
      - EMBEDDING_BACKEND=${EMBEDDING_BACKEND:-local}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_OUTPUT_DIM=1536
      - EMBED_DIM=1536
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - AUTO_BOOTSTRAP=1
    command:
      - /bin/sh
      - -c
      - |
        ha-rag-bootstrap && \
        uvicorn app.main:app \
          --host 0.0.0.0 --port 8000 \
          --log-config docker/uvicorn_log.ini
    env_file:
      - .env
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config_phase3.yaml:/app/config.yaml
      - ./litellm_ha_rag_hooks_phase3.py:/app/litellm_ha_rag_hooks_phase3.py
    command: ["--config", "/app/config.yaml", "--detailed_debug"]
    environment:
      - HA_RAG_API_URL=http://bridge:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    depends_on:
      - bridge
