version: "3.8"
services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - INFLUXD_REPORTING_DISABLED=true
  bridge:
    build: .
    environment:
      - EMBEDDING_BACKEND=gemini
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_OUTPUT_DIM=1536
      - EMBED_DIM=1536
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - AUTO_BOOTSTRAP=1
    command: >
      sh -c '
        python -m ha_rag_bridge.bootstrap || exit 1
        exec uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-config docker/uvicorn_log.ini
      '
