services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - "8123:8123"
    volumes:
      - ha_config:/config
    privileged: true
  bridge:
    build:
        context: .
        dockerfile: Dockerfile     # Point to the Dockerfile
        target: dev                # Use the dev stage
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-config docker/uvicorn_log.ini
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - EMBEDDING_BACKEND=gemini
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_OUTPUT_DIM=1536
      - EMBED_DIM=1536
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - AUTO_BOOTSTRAP=1
    depends_on:
      - arangodb
    env_file:
      - .env
  arangodb:
    image: arangodb:3.11
    ports:
      - "18529:8529"
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - arangodb_dev:/var/lib/arangodb3
    env_file:
      - .env
volumes:
  arangodb_dev:
  ha_config:
