[tool.poetry]
name = "ha-rag-bridge"        # bármi lehet, de legyen slug-formátumú
version = "0.1.0"             # semver
description = "Home-Assistant RAG bridge"
authors = ["lopeti <lovas.peter.hu@gmail.com>"]
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.116.1"
uvicorn = "^0.35.0"
httpx = "^0.27"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
