services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    ports:
      - "8123:8123"
    volumes:
      - ha_config:/config
    privileged: true
  bridge:
    build:
        context: .
        dockerfile: Dockerfile     # Point to the Dockerfile
        target: dev                # Use the dev stage
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --log-config docker/uvicorn_log.ini
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5678:5678"
      - "8000:8000"
    environment:
      - EMBEDDING_BACKEND=${EMBEDDING_BACKEND:-local}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_OUTPUT_DIM=1536
      - EMBED_DIM=768
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - AUTO_BOOTSTRAP=1
      # Log optimization settings
      - HA_RAG_LOG_LEVEL=TRACKING
      - HA_RAG_DETAILED_ERRORS=true
      - LOG_LEVEL=INFO
    profiles:
      - dev
    env_file:
      - .env
  arangodb:
    image: arangodb:3.11
    ports:
      - "18529:8529"
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - arangodb_dev:/var/lib/arangodb3
    env_file:
      - .env
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config_phase3.yaml:/app/config.yaml
      - ./litellm_ha_rag_hooks_phase3.py:/app/litellm_ha_rag_hooks_phase3.py
    command: ["--config", "/app/config.yaml", "--detailed_debug"]
    environment:
      - HA_RAG_API_URL=http://bridge:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LITELLM_LOG_LEVEL=INFO
      - LOG_PROMPTS=true
      - LOG_RESPONSES_PREVIEW=true
    profiles:
      - dev
    env_file:
      - .env
    depends_on:
      - bridge

volumes:
  arangodb_dev:
  ha_config:
