name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      arangodb:
        image: arangodb:3.11
        ports:
          - 8529:8529
        options: >
          --health-cmd="arangosh --server.endpoint tcp://127.0.0.1:8529 --server.password changeme --javascript.execute-string 'print(1)'" --health-interval=10s --health-timeout=5s --health-retries=5
        env:
          ARANGO_ROOT_PASSWORD: changeme
      influxdb:
        image: influxdb:2.7
        ports:
          - 8086:8086
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Copy env example
        run: cp .env.example .env
      - name: Start dev stack
        run: docker compose -f docker-compose.dev.yml up -d
      - name: Wait for ArangoDB
        run: |
          for i in {1..30}; do
            nc -z localhost 8529 && break
            sleep 2
          done
      - name: Run tests
        run: poetry run pytest -q
      - name: Stop dev stack
        run: docker compose -f docker-compose.dev.yml down
